spring:
  application:
    name: fridge-server



#    H2 - for dev server
#  datasource:
#    url: jdbc:h2:file:./data/fridge-db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
#    driver-class-name: org.h2.Driver
#    username: sa
#    password:
#
#  h2:
#    console:
#      enabled: true
#      path: /h2-console


#  ---mysql---
  datasource:
    url: jdbc:mysql://localhost:3307/fridge_db
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: never

springdoc:
  swagger-ui:
    path: /swagger-ui.html

server:
  address: 0.0.0.0

jwt:
  secret: mysecretkeythatishardtoguessandlongenough123
  access-exp: 900000        # 15분 (ms 단위)
  refresh-exp: 1209600000   # 14일 (ms 단위)
  enabled: false